### PR TITLE
Leave 2nd afternoon topic up for discussing

### PR DESCRIPTION
**Pull request by T45A**
Check concerning pull request for updated schedule

### CODE REVIEW

**Review by katrinleinweber — APPROVED** [review]
Fine with me! Thanks :-)

**Comment by katrinleinweber** [comment]
However, should we target the `gh-pages` branch directly, rather than the one #7 already pulled/merged?

**Comment by T45A** [comment]
Hi all, 
could you please check the new changes concerning schedule. 
What is your opinion about Day2 "Firefox Development Tool/Firebug" or "Python"?

Best wishes

Thomas

**Comment by katrinleinweber** [comment]
Let's not discuss more than 1 or 2 questions per issue.

1. What about:

> …should we target the gh-pages branch directly…

?

2. FxDT/FB: I use it, but wouldn't know how to teach. Probably https://www.youtube.com/results?search_query=firebug+anleitung are better sources. I could do the early [episodes of Python](https://librarycarpentry.org/lc-python-intro/), or we could help learners go through [PyCharm's Python course](https://www.jetbrains.com/pycharm-edu/learners/).

**Pull request merged**
